export const ordersTableColumns = {
  order_no: {
    id: "order_no",
    label: "Order No.",
    isSticky: true,
    position: 1,
    minConstraints: [150, 48] as [number, number],
    initialWidth: 150,
    width: 150,
  },
  date_placed: {
    id: "date_placed",
    label: "Date Placed",
    position: 2,
    minConstraints: [200, 48] as [number, number],
    initialWidth: 200,
    width: 200,
  },
  status: {
    id: "status",
    label: "Status",
    position: 3,
    minConstraints: [150, 48] as [number, number],
    initialWidth: 150,
    width: 150,
  },
  amount: {
    id: "amount",
    label: "Amount",
    position: 4,
    minConstraints: [100, 48] as [number, number],
    initialWidth: 100,
    width: 100,
  },
  address: {
    id: "address",
    label: "Address",
    position: 5,
    minConstraints: [400, 48] as [number, number],
    initialWidth: 400,
    width: 400,
  },
} as const;
